### ISSUE TITLE
missing default fields

### ISSUE THREAD

**Issue by moh-abk** [lankydan/rust-web-with-rocket#2]
Hi, great tutorial - I just tried it locally and when I send a POST request to create a new user, I get the following error - `Error: Couldn't parse JSON body: Error("missing field `id`", line: 7, column: 1)`

when I add the `id` to the body of the request it passes even though the `id` isn't used by Postgres

**Comment by lankydan** [comment]
I would love to try and fix this, but I havent touched rust in soo long it might take me a while. If you manage to figure out what is wrong with it I would be really happy to merge it in.

**Comment by peroo** [comment]
In case anyone else gets stuck on this:
Since the `id` field on `Person` isn't optional, serde refuses to deserialize the json data into a Person object. If you instead switch the insert handler to accept `InsertablePerson` and remove the call to `from_person` in repository.rs, it will work fine. Make sure to also derive `Deserialize` from serde in the `InsertablePerson` model.

**Comment by moh-abk** [comment]
Yeah that's how do do it @peroo . Have a struct and then another struct that has only the fields that get passed in by a form/user.
